# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
 
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-analyze:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - run:
          name: Add .NET Core SDK tools to PATH
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
          shell: bash
      - run:
          name: Install SonarScanner for .NET Core
          command: |
            dotnet tool install --global dotnet-sonarscanner
            dotnet sonarscanner begin /k:"my-api" /d:sonar.login=${SONAR_TOKEN}
          environment:
            SONAR_TOKEN: sqp_d0bb4b53e655a22e93b535dd37c4ab9a2681489e
      - run:
          name: Build and Test
          command: |
            dotnet build MyApi/MyApi.csproj --no-restore --configuration Release
            dotnet test MyApi.Tests/MyApi.Tests.csproj --no-restore --verbosity normal
      - run:
          name: SonarQube analysis
          command: |
            dotnet sonarscanner end /d:sonar.login=${SONAR_TOKEN}

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-analyze

